services:
  mongo:
    image: mongo:7.0
    container_name: mongo-light
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: link_checker_service
    command: ["--quiet", "--logpath", "/dev/null"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis-light
    restart: unless-stopped
    ports:
      - "6379:6379"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - mongo

volumes:
  mongo_data:
  metabase_data: