services:
  mongo:
    image: mongo:7.0
    container_name: mongo-light
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: ["--quiet", "--logpath", "/dev/null"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: